version: '3.9'
services:
  caesar:
    build:
      context: .
      dockerfile: ./dockerfile.prod
    ports:
      - '5000:5000'
    environment:
      - SECRET
      - REDIS_PASS
  caesar_dev:
    build:
      context: .
      dockerfile: ./dockerfile.dev
    ports:
      - '5000:5000'
    volumes:
      - ./caesar:/app/caesar
    environment:
      - SECRET="this-is-a-secret"
      - REDIS_PASS
  redis:
    image: 'redis:alpine'
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - '6379:6379'
    volumes:
      - ./redis/redis-data:/var/lib/redis
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master
